/* ============================================================
   build-static.js — pre-render the whole site to build/
   ------------------------------------------------------------
   Produces a fully static, Cloudflare-Pages-ready copy of the
   site under build/. Every HTML page, feed and header file is
   generated by REUSING the exact code paths server.js serves at
   request time (renderHtml + feeds.js + the same discovered
   articles and asset map), so the static output is byte-identical
   to the live server's — modulo the per-deploy ?v= token.

   server.js is required (not run): requiring it builds the same
   article/asset state without starting the HTTP listener.

   Run:  npm run build:static   (after npm run build)
   Out:  build/   (Cloudflare Pages "output directory")
   ============================================================ */

"use strict";

const fs = require("fs");
const path = require("path");

const {
  renderHtml,
  ARTICLES,
  // Slugs that PASSED validation — the same list the server routes on. The
  // build previously used discoverArticleSlugs() (every folder containing an
  // article.js), so a folder whose article the server REJECTED still got a
  // news/<slug>.html page written — which Cloudflare served with HTTP 200
  // where the dev server answered 404.
  VALID_ARTICLE_SLUGS,
  ARTICLE_SOCIAL_PATHS,
  PUBLICATION_YEARS,
  ARTICLE_SCRIPTS,
  ASSET_MAP,
  SECURITY_HEADERS,
  SITE_CFG,
  // Same cache-busting token the server stamps (CF_PAGES_COMMIT_SHA with a
  // timestamp fallback) — reused rather than re-derived so the two can never
  // drift. The ?v= token is the one allowed difference vs server output; the
  // parity test normalizes it on both sides.
  DEPLOY_VERSION,
} = require("./server.js");
// The public root surface (dependency-free leaf, shared with server.js and
// scripts/optimize-images.js): the served allowlist and the deploy contents
// derive from the same lists, so publishing a new root file is a single
// edit that updates both. Brand images copy plain (no variants exist for
// them); picture images pull their optimize-images siblings.
const {
  ROOT_PLAIN_FILES,
  ROOT_BRAND_IMAGES,
  ROOT_PICTURE_IMAGES,
} = require("./public-files.js");
const { buildSitemap, buildRss, buildFeed } = require("./feeds.js");
const { createSsrRenderer } = require("./ssr.js");
const { IMAGE_WIDTH_VARIANTS } = require("./ui-helpers.js");

const ROOT = __dirname;
const DEFAULT_OUT = path.join(ROOT, "build");

// Any unknown path renders the same not-found page (computePageMeta's not-found
// branch ignores the requested pathname), so 404.html is route-independent.
const NOT_FOUND_ROUTE = "/this-route-does-not-exist";

// Excluded from the build entirely — source, tooling, config, docs and the
// esbuild metafile. Asserted absent from build/ at the end. Keep this in sync
// with server.js's isPrivatePath deny rules.
const MUST_BE_ABSENT = [
  "server.js",
  "ssr.js",
  "build-static.js",
  "build.config.js",
  "feeds.js",
  "package.json",
  "package-lock.json",
  ".gitignore",
  "LICENSE",
  "README.md",
  "PUBLICATIONS.md",
  "news/README.md",
  "scripts",
  "test",
  "node_modules",
  "dist/manifest.json",
  // Uncompiled JSX sources are never copied (the hashed dist/ bundles are used).
  "app.jsx",
  "icons.jsx",
  "components",
  // Node-only allowlist leaf (required by server/build/image tooling).
  "public-files.js",
];

// Extensions the server classes as private EVERYWHERE, not just at the root
// (isPrivatePath: /\.(md|jsx)$/i) — the deep-copied folders (news/<slug>/,
// vendor/) must apply the same rule, or a draft-notes.md dropped next to an
// article would 404 on the dev server yet ship 200 on the deploy.
const PRIVATE_EXTENSIONS = /\.(md|jsx)$/i;

function log(msg) {
  console.log(msg);
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFile(outDir, relPath, contents) {
  const dest = path.join(outDir, relPath);
  ensureDir(path.dirname(dest));
  fs.writeFileSync(dest, contents);
}

// Copy a single source file (relative to ROOT) into the build if it exists.
function copyFile(outDir, relPath) {
  const src = path.join(ROOT, relPath);
  if (!fs.existsSync(src)) return false;
  const dest = path.join(outDir, relPath);
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
  return true;
}

// Copy an image plus its optimize-images siblings (.webp/.avif, including the
// -480/-960 width variants). The <picture> component and the home hero preload
// reference those variants, so they must ship for the rendered output to match
// the server byte-for-byte in the browser.
function copyImage(outDir, relPath) {
  copyFile(outDir, relPath);
  const noExt = relPath.replace(/\.[^.]+$/, "");
  for (const ext of [".webp", ".avif"]) {
    copyFile(outDir, noExt + ext);
    for (const w of IMAGE_WIDTH_VARIANTS) {
      copyFile(outDir, `${noExt}-${w}${ext}`);
    }
  }
}

// Recursively copy a directory (relative to ROOT) into the build. `skip` is an
// optional predicate on the absolute source path that excludes matching files.
// Dotfiles are always excluded: assertNoExcluded only sweeps the build ROOT,
// so a nested .DS_Store inside an article folder would otherwise ship
// silently into the deploy.
function copyDir(outDir, relDir, skip) {
  const src = path.join(ROOT, relDir);
  if (!fs.existsSync(src)) return;
  fs.cpSync(src, path.join(outDir, relDir), {
    recursive: true,
    filter: (s) =>
      !path.basename(s).startsWith(".") &&
      !PRIVATE_EXTENSIONS.test(path.basename(s)) &&
      !(skip && skip(s)),
  });
}

// The _headers file: reproduce SECURITY_HEADERS verbatim (so the CSP can never
// drift from the server) plus all four of cacheHeaderFor's cache classes:
//   HTML (and anything unmatched)  → no-cache, no-store, must-revalidate
//   /dist/*                        → public, max-age=31536000, immutable
//   feeds                          → public, max-age=3600
//   known asset extensions         → public, max-age=86400
//
// Cloudflare `_headers` matches the REQUEST path, not the resolved file, so the
// clean SPA URLs (/news, /publications, /news/<slug>) are extensionless and a
// `/*.html` rule alone would miss them — leaving the site's content pages
// without the server's no-store header. We therefore list every HTML route
// explicitly. The `/*` DEFAULT is no-store, not the asset class: an UNKNOWN
// extensionless path is answered by the 404 fallback page, and with an 86400
// default a visitor who hit a not-yet-published article URL kept the cached
// 404 for a day. Assets opt IN by extension instead (the server's whole
// mimeTypes set), so a missed extension degrades to uncached — never to a
// cached error page. Rules stay ordered general → specific (the broad /*
// default first, the exact paths last) so the intended value wins under BOTH
// of Cloudflare's precedence models (most-specific-wins and
// last-declared-wins). Security headers live on /* so they apply to every
// response, exactly as the server sets them on every request.
//
// Note: the server also serves ?v=-stamped non-dist assets as immutable, but
// `_headers` cannot match on a query string. Those assets fall into the 86400
// class here — they revalidate rather than serve stale bytes, and the ?v= token
// still busts caches on deploy because the URL string changes. This is the one
// intended, harmless gap.
const ASSET_EXTENSIONS = [
  "css", "js", "json", "webmanifest", "txt", "xml",
  "png", "jpg", "jpeg", "svg", "ico", "webp", "avif",
  "woff2", "woff", "mp4", "webm", "vtt", "pdf",
];
function buildHeadersFile(securityHeaders, htmlPathnames) {
  const NO_STORE = "Cache-Control: no-cache, no-store, must-revalidate";
  const lines = [];

  // Global default: security headers on every response; no-store for anything
  // no later rule claims (above all, the 404 fallback for unknown paths).
  lines.push("/*");
  for (const [name, value] of Object.entries(securityHeaders)) {
    lines.push(`  ${name}: ${value}`);
  }
  lines.push(`  ${NO_STORE}`);
  lines.push("");

  // Known asset extensions: the daily-revalidate class. Cloudflare's `*`
  // crosses path segments, so /*.js also covers /news/<slug>/article.js.
  for (const ext of ASSET_EXTENSIONS) {
    lines.push(`/*.${ext}`);
    lines.push("  Cache-Control: public, max-age=86400");
    lines.push("");
  }

  // Feeds: public, max-age=3600 — exact paths declared AFTER /*.xml and
  // /*.json so the feed value wins under both precedence models. The
  // Content-Type is pinned too: Cloudflare derives types from the extension
  // (application/xml, application/json), while the server — and the
  // <link rel="alternate" type=…> declarations in every page head — use the
  // feeds' REGISTERED media types; without these rules the deploy served a
  // type the pages themselves contradict.
  const FEED_TYPES = {
    "/sitemap.xml": "application/xml; charset=utf-8",
    "/rss.xml": "application/rss+xml; charset=utf-8",
    "/feed.json": "application/feed+json; charset=utf-8",
  };
  for (const [feed, type] of Object.entries(FEED_TYPES)) {
    lines.push(feed);
    lines.push("  Cache-Control: public, max-age=3600");
    lines.push(`  Content-Type: ${type}`);
    lines.push("");
  }

  // Content-hashed bundles never change: immutable (declared after /*.js so
  // the longer-lived value is the later, winning declaration).
  lines.push("/dist/*");
  lines.push("  Cache-Control: public, max-age=31536000, immutable");
  lines.push("");

  // Every HTML response is no-store. *.html covers 404.html / any direct .html
  // hit; the explicit clean URLs cover the extensionless SPA routes.
  lines.push("/*.html");
  lines.push(`  ${NO_STORE}`);
  lines.push("");
  for (const pathname of htmlPathnames) {
    lines.push(pathname);
    lines.push(`  ${NO_STORE}`);
    lines.push("");
  }

  return lines.join("\n");
}

// The build's OWN SSR renderer, pinned to the same ASSET_MAP snapshot the
// script tags are rewritten from — so the pre-rendered body and the bundles
// that hydrate it can never come from different builds, even if a watch
// rebuild lands mid-build. createSsrRenderer THROWS when the compiled
// bundles are missing: for the dev server that degrades to an empty #root,
// but a DEPLOY artifact without its body would silently lose the whole
// point of the pre-render, so here the build must fail loudly instead.
// Created inside buildStatic (not at module load) so merely requiring this
// module — the parity test imports MUST_BE_ABSENT — needs no built bundles.
let ssr = null;

function render(pathname) {
  const html = renderHtml(fs.readFileSync(path.join(ROOT, "index.html"), "utf8"), pathname, {
    deployVersion: DEPLOY_VERSION,
    articleScripts: ARTICLE_SCRIPTS,
    assetMap: ASSET_MAP,
    renderApp: ssr.renderApp,
  });
  // Belt-and-braces: a page whose #root came back empty (a per-route render
  // throw is swallowed into "" on the server path) must not ship. The check
  // is for the EMPTY marker's presence, not a "filled" prefix — the previous
  // `!html.includes('<div id="root"><')` was inert, because that prefix is
  // also a substring of the empty `<div id="root"></div>` (its closing tag
  // starts with the same "<").
  if (html.includes('<div id="root"></div>')) {
    throw new Error(`build: pre-rendered body missing for ${pathname}`);
  }
  return html;
}

function assertNoExcluded(outDir) {
  const leaked = [];
  for (const rel of MUST_BE_ABSENT) {
    if (fs.existsSync(path.join(outDir, rel))) leaked.push(rel);
  }
  // No dotfiles at the build root either.
  for (const entry of fs.readdirSync(outDir)) {
    if (entry.startsWith(".")) leaked.push(entry);
  }
  if (leaked.length) {
    throw new Error(`Excluded/private files leaked into build/: ${leaked.join(", ")}`);
  }
}

function buildStatic({ outDir = DEFAULT_OUT } = {}) {
  // SSR renderer first: with no compiled bundles this throws immediately —
  // a deploy artifact must never ship with empty page bodies.
  ssr = createSsrRenderer({ assetMap: ASSET_MAP, articleSlugs: VALID_ARTICLE_SLUGS });

  // Clean slate so a removed article/asset never lingers in the output.
  fs.rmSync(outDir, { recursive: true, force: true });
  ensureDir(outDir);

  const slugs = VALID_ARTICLE_SLUGS;

  // --- 1. Pre-render one HTML file per route -------------------------------
  // FLAT files (news.html), not directory indexes (news/index.html): Cloudflare
  // Pages serves foo.html at the slash-less /foo and 308-redirects /foo/ there,
  // while foo/index.html canonicalizes the other way (/foo → /foo/). Every
  // canonical tag, og:url, sitemap <loc> and feed link uses the slash-less
  // form, so the flat layout is the one whose served URLs match the metadata
  // without a redirect hop. Article asset folders (news/<slug>/) coexist with
  // the news/<slug>.html pages.
  const htmlRoutes = [
    { pathname: "/", out: "index.html" },
    { pathname: "/news", out: "news.html" },
    { pathname: "/publications", out: "publications.html" },
    ...slugs.map((slug) => ({ pathname: `/news/${slug}`, out: `news/${slug}.html` })),
  ];
  for (const route of htmlRoutes) {
    writeFile(outDir, route.out, render(route.pathname));
  }
  // Cloudflare serves 404.html with HTTP 404 for unmatched paths.
  writeFile(outDir, "404.html", render(NOT_FOUND_ROUTE));

  // --- 2. Feeds (same builders the server uses) ----------------------------
  writeFile(outDir, "sitemap.xml", buildSitemap({ articles: ARTICLES, siteCfg: SITE_CFG, publicationYears: PUBLICATION_YEARS }));
  writeFile(outDir, "rss.xml", buildRss({ articles: ARTICLES, siteCfg: SITE_CFG }));
  writeFile(outDir, "feed.json", buildFeed({ articles: ARTICLES, siteCfg: SITE_CFG, socialImages: ARTICLE_SOCIAL_PATHS }));

  // --- 3. Cloudflare config ------------------------------------------------
  writeFile(outDir, "_headers", buildHeadersFile(SECURITY_HEADERS, htmlRoutes.map((r) => r.pathname)));
  // Every flat HTML file 301s to its clean URL, so the pre-rendered bodies
  // are never reachable under a second (.html) address — a direct hit on
  // /news.html used to serve a real page that the client router then tore
  // down as a 404 view. (Cloudflare already 308s /foo/ → /foo itself.)
  // 404.html joins the same rule: Cloudflare serves it INTERNALLY for
  // unmatched paths (no request to /404.html involved), so redirecting the
  // direct address costs nothing and closes the one remaining second-address
  // page. The dev server mirrors this whole map (FLAT_HTML_REDIRECTS).
  writeFile(
    outDir,
    "_redirects",
    "/index.html  /  301\n" +
      "/404.html  /  301\n" +
      htmlRoutes
        .filter((r) => r.out !== "index.html")
        .map((r) => `/${r.out}  ${r.pathname}  301\n`)
        .join("")
  );

  // --- 4. Public assets ----------------------------------------------------
  for (const rel of ROOT_PLAIN_FILES) copyFile(outDir, rel);
  for (const rel of ROOT_BRAND_IMAGES) copyFile(outDir, rel);
  for (const rel of ROOT_PICTURE_IMAGES) copyImage(outDir, rel);
  copyDir(outDir, "vendor");
  // dist/: only the CURRENT hashed bundles — the ones the asset map (and thus
  // the rendered HTML) references. esbuild leaves older-hash siblings behind
  // after local rebuilds, and copying the whole directory shipped that dead
  // weight into the deploy output. Never the esbuild metafile. If the asset
  // map is somehow empty, fall back to copying everything (minus the metafile)
  // rather than shipping no scripts at all.
  const liveDistFiles = new Set(
    Object.values(ASSET_MAP).map((p) => path.join(ROOT, p.replace(/^\//, "")))
  );
  copyDir(outDir, "dist", (src) => {
    if (path.basename(src) === "manifest.json") return true;
    if (liveDistFiles.size === 0) return false;
    if (fs.statSync(src).isDirectory()) return false;
    return !liveDistFiles.has(src);
  });
  // Each discovered article folder ships whole: article.js + images + video.
  for (const slug of slugs) copyDir(outDir, path.join("news", slug));

  // --- 5. Safety: nothing private may have leaked in ------------------------
  assertNoExcluded(outDir);

  log(`Static build complete → ${path.relative(ROOT, outDir) || outDir}`);
  log(`  ${htmlRoutes.length} HTML pages + 404.html, ${slugs.length} articles`);
  return { outDir, htmlRoutes, slugs };
}

// MUST_BE_ABSENT / assertNoExcluded are exported for the parity test, which
// consumes the SAME list this module enforces (a hand copy there could drift)
// and asserts the guard actually throws on a planted private file.
// DEPLOY_VERSION is deliberately not re-exported — server.js is its one home.
module.exports = { buildStatic, MUST_BE_ABSENT, assertNoExcluded };

if (require.main === module) {
  buildStatic();
}
