/* ============================================================
   build-static.js — pre-render the whole site to build/
   ------------------------------------------------------------
   Produces a fully static, Cloudflare-Pages-ready copy of the
   site under build/. Every HTML page, feed and header file is
   generated by REUSING the exact code paths server.js serves at
   request time (renderHtml + feeds.js + the same discovered
   articles and asset map), so the static output is byte-identical
   to the live server's — modulo the per-deploy ?v= token.

   server.js is required (not run): requiring it builds the same
   article/asset state without starting the HTTP listener.

   Run:  npm run build:static   (after npm run build)
   Out:  build/   (Cloudflare Pages "output directory")
   ============================================================ */

"use strict";

const fs = require("fs");
const path = require("path");

const {
  renderHtml,
  discoverArticleSlugs,
  ARTICLES,
  PUBLICATION_YEARS,
  ARTICLE_SCRIPTS,
  ASSET_MAP,
  SECURITY_HEADERS,
  SITE_CFG,
  // Same cache-busting token the server stamps (CF_PAGES_COMMIT_SHA with a
  // timestamp fallback) — reused rather than re-derived so the two can never
  // drift. The ?v= token is the one allowed difference vs server output; the
  // parity test normalizes it on both sides.
  DEPLOY_VERSION,
} = require("./server.js");
const { buildSitemap, buildRss, buildFeed } = require("./feeds.js");
const { IMAGE_WIDTH_VARIANTS } = require("./ui-helpers.js");

const ROOT = __dirname;
const DEFAULT_OUT = path.join(ROOT, "build");

// Any unknown path renders the same not-found page (computePageMeta's not-found
// branch ignores the requested pathname), so 404.html is route-independent.
const NOT_FOUND_ROUTE = "/this-route-does-not-exist";

// Public root files copied verbatim. Image bases additionally pull their
// optimize-images siblings (.webp/.avif) via copyImage below.
const ROOT_PLAIN_FILES = [
  "styles.css",
  "site.config.js",
  "routes.js",
  "article-schema.js",
  "ui-helpers.js",
  "data.js",
  "site.webmanifest",
  "robots.txt",
  "favicon.ico",
  "favicon.svg",
  // The hero's "Download CV" target (site.config.js cvPath).
  "lampros-konstantellos-cv.pdf",
];

const ROOT_IMAGE_BASES = [
  "favicon-16x16.png",
  "favicon-32x32.png",
  "favicon-48x48.png",
  "favicon-64x64.png",
  "favicon-96x96.png",
  "favicon-128x128.png",
  "icon-192.png",
  "icon-256.png",
  "icon-512.png",
  "apple-touch-icon.png",
  "og-image.jpg",
  "lampros-konstantellos-picture.jpg",
];

// Excluded from the build entirely — source, tooling, config, docs and the
// esbuild metafile. Asserted absent from build/ at the end. Keep this in sync
// with server.js's isPrivatePath deny rules.
const MUST_BE_ABSENT = [
  "server.js",
  "build-static.js",
  "feeds.js",
  "package.json",
  "package-lock.json",
  ".gitignore",
  "LICENSE",
  "README.md",
  "PUBLICATIONS.md",
  "news/README.md",
  "scripts",
  "test",
  "node_modules",
  "dist/manifest.json",
  // Uncompiled JSX sources are never copied (the hashed dist/ bundles are used).
  "app.jsx",
  "icons.jsx",
  "components",
];

function log(msg) {
  console.log(msg);
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFile(outDir, relPath, contents) {
  const dest = path.join(outDir, relPath);
  ensureDir(path.dirname(dest));
  fs.writeFileSync(dest, contents);
}

// Copy a single source file (relative to ROOT) into the build if it exists.
function copyFile(outDir, relPath) {
  const src = path.join(ROOT, relPath);
  if (!fs.existsSync(src)) return false;
  const dest = path.join(outDir, relPath);
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
  return true;
}

// Copy an image plus its optimize-images siblings (.webp/.avif, including the
// -480/-960 width variants). The <picture> component and the home hero preload
// reference those variants, so they must ship for the rendered output to match
// the server byte-for-byte in the browser.
function copyImage(outDir, relPath) {
  copyFile(outDir, relPath);
  const noExt = relPath.replace(/\.[^.]+$/, "");
  for (const ext of [".webp", ".avif"]) {
    copyFile(outDir, noExt + ext);
    for (const w of IMAGE_WIDTH_VARIANTS) {
      copyFile(outDir, `${noExt}-${w}${ext}`);
    }
  }
}

// Recursively copy a directory (relative to ROOT) into the build. `skip` is an
// optional predicate on the absolute source path that excludes matching files.
function copyDir(outDir, relDir, skip) {
  const src = path.join(ROOT, relDir);
  if (!fs.existsSync(src)) return;
  fs.cpSync(src, path.join(outDir, relDir), {
    recursive: true,
    filter: skip ? (s) => !skip(s) : undefined,
  });
}

// The _headers file: reproduce SECURITY_HEADERS verbatim (so the CSP can never
// drift from the server) plus all four of cacheHeaderFor's cache classes:
//   HTML        → no-cache, no-store, must-revalidate
//   /dist/*     → public, max-age=31536000, immutable
//   feeds       → public, max-age=3600
//   everything  → public, max-age=86400
//
// Cloudflare `_headers` matches the REQUEST path, not the resolved file, so the
// clean SPA URLs (/news, /publications, /news/<slug>) are extensionless and a
// `/*.html` rule alone would miss them — leaving the site's content pages
// without the server's no-store header. We therefore list every HTML route
// explicitly. Rules are ordered general → specific (the broad /* default first,
// the exact paths last) so the intended value wins under BOTH of Cloudflare's
// precedence models (most-specific-wins and last-declared-wins). Security
// headers live on /* so they apply to every response, exactly as the server
// sets them on every request.
//
// Note: the server also serves ?v=-stamped non-dist assets as immutable, but
// `_headers` cannot match on a query string. Those assets fall into the 86400
// class here — they revalidate rather than serve stale bytes, and the ?v= token
// still busts caches on deploy because the URL string changes. This is the one
// intended, harmless gap.
function buildHeadersFile(securityHeaders, htmlPathnames) {
  const NO_STORE = "Cache-Control: no-cache, no-store, must-revalidate";
  const lines = [];

  // Global default: security headers on every response + the catch-all asset
  // cache class. Overridden below for HTML routes, feeds and hashed bundles.
  lines.push("/*");
  for (const [name, value] of Object.entries(securityHeaders)) {
    lines.push(`  ${name}: ${value}`);
  }
  lines.push("  Cache-Control: public, max-age=86400");
  lines.push("");

  // Feeds: public, max-age=3600 (exact paths, no overlap with assets).
  for (const feed of ["/sitemap.xml", "/rss.xml", "/feed.json"]) {
    lines.push(feed);
    lines.push("  Cache-Control: public, max-age=3600");
    lines.push("");
  }

  // Content-hashed bundles never change: immutable.
  lines.push("/dist/*");
  lines.push("  Cache-Control: public, max-age=31536000, immutable");
  lines.push("");

  // Every HTML response is no-store. *.html covers 404.html / any direct .html
  // hit; the explicit clean URLs cover the extensionless SPA routes.
  lines.push("/*.html");
  lines.push(`  ${NO_STORE}`);
  lines.push("");
  for (const pathname of htmlPathnames) {
    lines.push(pathname);
    lines.push(`  ${NO_STORE}`);
    lines.push("");
  }

  return lines.join("\n");
}

function render(pathname) {
  return renderHtml(fs.readFileSync(path.join(ROOT, "index.html"), "utf8"), pathname, {
    deployVersion: DEPLOY_VERSION,
    articleScripts: ARTICLE_SCRIPTS,
    assetMap: ASSET_MAP,
  });
}

function assertNoExcluded(outDir) {
  const leaked = [];
  for (const rel of MUST_BE_ABSENT) {
    if (fs.existsSync(path.join(outDir, rel))) leaked.push(rel);
  }
  // No dotfiles at the build root either.
  for (const entry of fs.readdirSync(outDir)) {
    if (entry.startsWith(".")) leaked.push(entry);
  }
  if (leaked.length) {
    throw new Error(`Excluded/private files leaked into build/: ${leaked.join(", ")}`);
  }
}

function buildStatic({ outDir = DEFAULT_OUT } = {}) {
  // Clean slate so a removed article/asset never lingers in the output.
  fs.rmSync(outDir, { recursive: true, force: true });
  ensureDir(outDir);

  const slugs = discoverArticleSlugs();

  // --- 1. Pre-render one HTML file per route -------------------------------
  // FLAT files (news.html), not directory indexes (news/index.html): Cloudflare
  // Pages serves foo.html at the slash-less /foo and 308-redirects /foo/ there,
  // while foo/index.html canonicalizes the other way (/foo → /foo/). Every
  // canonical tag, og:url, sitemap <loc> and feed link uses the slash-less
  // form, so the flat layout is the one whose served URLs match the metadata
  // without a redirect hop. Article asset folders (news/<slug>/) coexist with
  // the news/<slug>.html pages.
  const htmlRoutes = [
    { pathname: "/", out: "index.html" },
    { pathname: "/news", out: "news.html" },
    { pathname: "/publications", out: "publications.html" },
    ...slugs.map((slug) => ({ pathname: `/news/${slug}`, out: `news/${slug}.html` })),
  ];
  for (const route of htmlRoutes) {
    writeFile(outDir, route.out, render(route.pathname));
  }
  // Cloudflare serves 404.html with HTTP 404 for unmatched paths.
  writeFile(outDir, "404.html", render(NOT_FOUND_ROUTE));

  // --- 2. Feeds (same builders the server uses) ----------------------------
  writeFile(outDir, "sitemap.xml", buildSitemap({ articles: ARTICLES, siteCfg: SITE_CFG, publicationYears: PUBLICATION_YEARS }));
  writeFile(outDir, "rss.xml", buildRss({ articles: ARTICLES, siteCfg: SITE_CFG }));
  writeFile(outDir, "feed.json", buildFeed({ articles: ARTICLES, siteCfg: SITE_CFG }));

  // --- 3. Cloudflare config ------------------------------------------------
  writeFile(outDir, "_headers", buildHeadersFile(SECURITY_HEADERS, htmlRoutes.map((r) => r.pathname)));
  writeFile(outDir, "_redirects", "/index.html  /  301\n");

  // --- 4. Public assets ----------------------------------------------------
  for (const rel of ROOT_PLAIN_FILES) copyFile(outDir, rel);
  for (const rel of ROOT_IMAGE_BASES) copyImage(outDir, rel);
  copyDir(outDir, "vendor");
  // dist/: only the CURRENT hashed bundles — the ones the asset map (and thus
  // the rendered HTML) references. esbuild leaves older-hash siblings behind
  // after local rebuilds, and copying the whole directory shipped that dead
  // weight into the deploy output. Never the esbuild metafile. If the asset
  // map is somehow empty, fall back to copying everything (minus the metafile)
  // rather than shipping no scripts at all.
  const liveDistFiles = new Set(
    Object.values(ASSET_MAP).map((p) => path.join(ROOT, p.replace(/^\//, "")))
  );
  copyDir(outDir, "dist", (src) => {
    if (path.basename(src) === "manifest.json") return true;
    if (liveDistFiles.size === 0) return false;
    if (fs.statSync(src).isDirectory()) return false;
    return !liveDistFiles.has(src);
  });
  // Each discovered article folder ships whole: article.js + images + video.
  for (const slug of slugs) copyDir(outDir, path.join("news", slug));

  // --- 5. Safety: nothing private may have leaked in ------------------------
  assertNoExcluded(outDir);

  log(`Static build complete → ${path.relative(ROOT, outDir) || outDir}`);
  log(`  ${htmlRoutes.length} HTML pages + 404.html, ${slugs.length} articles`);
  return { outDir, htmlRoutes, slugs };
}

module.exports = { buildStatic, DEPLOY_VERSION };

if (require.main === module) {
  buildStatic();
}
